# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: replicator.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'replicator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10replicator.proto\"\x9a\x01\n\nMessageMOM\x12\x11\n\toperation\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x10\n\x08\x65xchange\x18\x03 \x01(\t\x12\x13\n\x0brouting_key\x18\x04 \x01(\t\x12\x14\n\x0cmessage_date\x18\x05 \x01(\x04\x12\x0c\n\x04\x62ody\x18\x06 \x01(\t\x12\x10\n\x08username\x18\x07 \x01(\t\x12\x0e\n\x06userid\x18\x08 \x01(\t\"%\n\x12ReplicationSuccess\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x46\n\tReplicate\x12\x39\n\x13PopulateReplication\x12\x0b.MessageMOM\x1a\x13.ReplicationSuccess\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'replicator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEMOM']._serialized_start=21
  _globals['_MESSAGEMOM']._serialized_end=175
  _globals['_REPLICATIONSUCCESS']._serialized_start=177
  _globals['_REPLICATIONSUCCESS']._serialized_end=214
  _globals['_REPLICATE']._serialized_start=216
  _globals['_REPLICATE']._serialized_end=286
# @@protoc_insertion_point(module_scope)
